build:
    #!/usr/bin/env bash
    npx tsc
    cp ./*.css ./dist
    cp ./icons/*.png ./dist
    cp ./icons/*.ico ./dist
    cp ./icons/*.svg ./dist
    cp ./fonts/* ./dist

dot:
    dot -Tpng imgviewer.dot -o imgviewer.png
