build:
    #!/usr/bin/env bash
    tsc
    cp ./css/*.css ./dist
    cp ./icons/*.png ./dist
    cp ./icons/*.ico ./dist
    cp ./icons/*.svg ./dist
    cp ./fonts/* ./dist
    cp ./external/* ./dist

dot:
    dot -Tpng imgviewer.dot -o imgviewer.png
