name: filehub CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-linux:
    name: Build (Linux)
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Install nix"
        uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: "Build"
        run: |
          nix build

      - name: "Upload binary"
        uses: actions/upload-artifact@v4
        with:
          name: filehub-linux-x86-64
          path: ./result/bin/filehub


  build-macos-m1:
    name: Build (macOS m1)
    runs-on: macos-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Install nix"
        uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: "Build"
        run: |
          nix build

      - name: "Upload binary"
        uses: actions/upload-artifact@v4
        with:
          name: filehub-macos-m1
          path: ./result/bin/filehub


  build-windows:
    name: Build (windows)
    runs-on: windows-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      # make sure this follows the current toolchain version
      - uses: haskell-actions/setup@v2
        with:
          ghc-version: '9.6.6'
          cabal-version: '3.12.1.0'

      - name: Update cabal index
        run: cabal update

      - name: Build
        run: cabal build all

      - name: Copy executable
        run: |
          mkdir -Force dist
          cp $(Get-ChildItem -Recurse -Filter '*.exe' | Select-Object -First 1).FullName dist\filehub.exe

      - name: Install UPX
        run: choco install upx -y

      - name: Compress with UPX
        run: |
          upx --best --lzma dist\filehub.exe

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: filehub-windows
          path: dist/filehub.exe
